#!/bin/sh
### BEGIN INIT INFO
# Provides:          dalek
# Required-Start:    $local_fs $syslog $bluetooth
# Required-Stop:     $local_fs $syslog $bluetooth
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Description:       Dalek control software
### END INIT INFO

# configure the following and copy this file to: /etc/init.d/dalek
# then run: update-rc.d dalek defaults

NAME=dalek
DIR=/home/pi/dalek
SCRIPT=$DIR/dalek.py
RUNAS=pi

PIDFILE=/var/run/dalek.pid
 
start() {
  if [ -f /var/run/$PIDNAME ] && kill -0 $(cat /var/run/$PIDNAME); then
    echo 'Service already running' >&2
    return 1
  fi
  echo 'Starting service…' >&2
  cd $DIR;
  su -c "$SCRIPT 2>&1 | logger -t '$NAME' & jobs -p" "$RUNAS" >"$PIDFILE"
  echo 'Service started' >&2
}
 
stop() {
  if [ ! -f "$PIDFILE" ] || ! kill -0 $(cat "$PIDFILE"); then
    echo 'Service not running' >&2
    return 1
  fi
  echo 'Stopping service…' >&2
  kill -15 $(cat "$PIDFILE") && rm -f "$PIDFILE"
  echo 'Service stopped' >&2
}

case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  restart)
    stop
    start
    ;;
  *)
    echo "Usage: $0 {start|stop|restart}"
esac
